[package]
name = "b64"
version = "0.1.0"
authors = ["lowit <ea@lowit.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { git = "https://github.com/clap-rs/clap/" }
base64 = "0.11.0"
